# Generated by Django 4.1.2 on 2022-11-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_concert_city_alter_concert_status_targetinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="QticketsSalesInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qticketsConcertID",
                    models.CharField(max_length=6, verbose_name="ID продажи билетов"),
                ),
                (
                    "qticketsAccountName",
                    models.CharField(
                        max_length=30, verbose_name="Название аккаунта Qtickets"
                    ),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.concert"
                    ),
                ),
            ],
        ),
    ]
