# Generated by Django 4.1.2 on 2022-11-06 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_qticketssalesinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qticketssalesinfo",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.concert"
            ),
        ),
        migrations.AlterField(
            model_name="targetinfo",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.concert"
            ),
        ),
    ]
